# Generated by Django 4.0.3 on 2022-03-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id_athlete', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Sex', models.CharField(max_length=1)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Team', models.CharField(max_length=100)),
                ('NOC', models.CharField(max_length=4)),
                ('Games', models.CharField(max_length=255)),
                ('Year', models.IntegerField()),
                ('Season', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Sport', models.CharField(max_length=255)),
                ('Event', models.CharField(max_length=255)),
                ('Medal', models.CharField(max_length=255)),
                ('Create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
